version: '3'
services:

    php-apache:
        container_name: website 
        build: ./Novel
        volumes:
          - ./Novel:/var/www/html
        environment:
          - MYSQL_DBHOST=db 
          - MYSQL_DAPORT=9000
          - MYSQL_DAUSER=root
          - MYSQL_DAPASS=root
          - MYSQL_DANAME=
          - file_uploads=On
        ports:
          - 8000:80
        depends_on:
          - db

    db:
      image: mysql:latest
      container_name: DB
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bookstore
      ports:
          - "9000:3306"
      volumes:
          - ./my.cnf:/etc/mysql/my.cnf
          - DB_data:/var/lib/mysql

    phpmyadmin : 
      image : phpmyadmin:latest
      restart : always 
      ports:
        - 8080:80 
      environment : 
        PMA_HOST: DB
        UPLOAD_LIMIT: 3000M
      depends_on:
        - db
      
    redis:
      image: redis:latest
      ports:
        - "6379:6379"


    # python-script:
    #     build: ./web_scriping
    #     volumes:
    #       - ./web_scriping:/app
    #     depends_on:
    #       - db
    #     environment:
    #       - MYSQL_HOST=db
    #       - MYSQL_USER=root
    #       - MYSQL_PASSWORD=root
    #       - MYSQL_DB=bookstore
volumes:
  DB_data:
